export const LANGUAGE_OPTIONS = [
    // --- Your original order (preferred) ---
    { code: 'en_XX', name: 'English', shortcut: 'EN', emoji: '🇬🇧' },
    { code: 'cs_CZ', name: 'Czech', shortcut: 'CS', emoji: '🇨🇿' },
    { code: 'it_IT', name: 'Italian', shortcut: 'IT', emoji: '🇮🇹' },
    { code: 'fr_XX', name: 'French', shortcut: 'FR', emoji: '🇫🇷' },
    { code: 'de_DE', name: 'German', shortcut: 'DE', emoji: '🇩🇪' },
    { code: 'es_XX', name: 'Spanish', shortcut: 'ES', emoji: '🇪🇸' },
    { code: 'ru_RU', name: 'Russian', shortcut: 'RU', emoji: '🇷🇺' },
    { code: 'zh_CN', name: 'Chinese (Simplified)', shortcut: 'ZH', emoji: '🇨🇳' },
    { code: 'ar_AR', name: 'Arabic', shortcut: 'AR', emoji: '🇦🇪' },
    { code: 'hi_IN', name: 'Hindi', shortcut: 'HI', emoji: '🇮🇳' },
    { code: 'pl_PL', name: 'Polish', shortcut: 'PL', emoji: '🇵🇱' },
    { code: 'pt_XX', name: 'Portuguese', shortcut: 'PT', emoji: '🇵🇹' },
    { code: 'tr_TR', name: 'Turkish', shortcut: 'TR', emoji: '🇹🇷' },
    { code: 'vi_VN', name: 'Vietnamese', shortcut: 'VI', emoji: '🇻🇳' },

    // --- European ---
    { code: 'nl_NL', name: 'Dutch', shortcut: 'NL', emoji: '🇳🇱' },
    { code: 'sv_SE', name: 'Swedish', shortcut: 'SV', emoji: '🇸🇪' },
    { code: 'da_DK', name: 'Danish', shortcut: 'DA', emoji: '🇩🇰' },
    { code: 'fi_FI', name: 'Finnish', shortcut: 'FI', emoji: '🇫🇮' },
    { code: 'no_NO', name: 'Norwegian', shortcut: 'NO', emoji: '🇳🇴' },
    { code: 'is_IS', name: 'Icelandic', shortcut: 'IS', emoji: '🇮🇸' },
    { code: 'ro_RO', name: 'Romanian', shortcut: 'RO', emoji: '🇷🇴' },
    { code: 'hu_HU', name: 'Hungarian', shortcut: 'HU', emoji: '🇭🇺' },
    { code: 'bg_BG', name: 'Bulgarian', shortcut: 'BG', emoji: '🇧🇬' },
    { code: 'el_GR', name: 'Greek', shortcut: 'EL', emoji: '🇬🇷' },
    { code: 'hr_HR', name: 'Croatian', shortcut: 'HR', emoji: '🇭🇷' },
    { code: 'uk_UA', name: 'Ukrainian', shortcut: 'UK', emoji: '🇺🇦' },
    { code: 'sk_SK', name: 'Slovak', shortcut: 'SK', emoji: '🇸🇰' },
    { code: 'sl_SI', name: 'Slovenian', shortcut: 'SL', emoji: '🇸🇮' },
    { code: 'lt_LT', name: 'Lithuanian', shortcut: 'LT', emoji: '🇱🇹' },
    { code: 'lv_LV', name: 'Latvian', shortcut: 'LV', emoji: '🇱🇻' },
    { code: 'et_EE', name: 'Estonian', shortcut: 'ET', emoji: '🇪🇪' },
    { code: 'sr_RS', name: 'Serbian', shortcut: 'SR', emoji: '🇷🇸' },
    { code: 'mk_MK', name: 'Macedonian', shortcut: 'MK', emoji: '🇲🇰' },
    { code: 'bs_BA', name: 'Bosnian', shortcut: 'BS', emoji: '🇧🇦' },
    { code: 'sq_AL', name: 'Albanian', shortcut: 'SQ', emoji: '🇦🇱' },
    { code: 'mt_MT', name: 'Maltese', shortcut: 'MT', emoji: '🇲🇹' },
    { code: 'ga_IE', name: 'Irish', shortcut: 'GA', emoji: '🇮🇪' },
    { code: 'cy_GB', name: 'Welsh', shortcut: 'CY', emoji: '🏴' },
    { code: 'ca_ES', name: 'Catalan', shortcut: 'CA', emoji: '🇪🇸' },
    { code: 'eu_ES', name: 'Basque', shortcut: 'EU', emoji: '🇪🇸' },
    { code: 'gl_ES', name: 'Galician', shortcut: 'GL', emoji: '🇪🇸' },
    { code: 'af_ZA', name: 'Afrikaans', shortcut: 'AF', emoji: '🇿🇦' },

    // --- East Asia & Oceania ---
    { code: 'zh_TW', name: 'Chinese (Traditional)', shortcut: 'ZH-TW', emoji: '🇹🇼' },
    { code: 'ja_XX', name: 'Japanese', shortcut: 'JA', emoji: '🇯🇵' },
    { code: 'ko_KR', name: 'Korean', shortcut: 'KO', emoji: '🇰🇷' },
    { code: 'th_TH', name: 'Thai', shortcut: 'TH', emoji: '🇹🇭' },
    { code: 'id_ID', name: 'Indonesian', shortcut: 'ID', emoji: '🇮🇩' },
    { code: 'ms_MY', name: 'Malay', shortcut: 'MS', emoji: '🇲🇾' },
    { code: 'fil_PH', name: 'Filipino', shortcut: 'FIL', emoji: '🇵🇭' },
    { code: 'tl_PH', name: 'Tagalog', shortcut: 'TL', emoji: '🇵🇭' },
    { code: 'ceb_PH', name: 'Cebuano', shortcut: 'CEB', emoji: '🇵🇭' },
    { code: 'jv_ID', name: 'Javanese', shortcut: 'JV', emoji: '🇮🇩' },
    { code: 'su_ID', name: 'Sundanese', shortcut: 'SU', emoji: '🇮🇩' },

    // --- South Asia ---
    { code: 'bn_BD', name: 'Bengali', shortcut: 'BN', emoji: '🇧🇩' },
    { code: 'ur_PK', name: 'Urdu', shortcut: 'UR', emoji: '🇵🇰' },
    { code: 'ta_IN', name: 'Tamil', shortcut: 'TA', emoji: '🇮🇳' },
    { code: 'te_IN', name: 'Telugu', shortcut: 'TE', emoji: '🇮🇳' },
    { code: 'ml_IN', name: 'Malayalam', shortcut: 'ML', emoji: '🇮🇳' },
    { code: 'gu_IN', name: 'Gujarati', shortcut: 'GU', emoji: '🇮🇳' },
    { code: 'mr_IN', name: 'Marathi', shortcut: 'MR', emoji: '🇮🇳' },
    { code: 'pa_IN', name: 'Punjabi', shortcut: 'PA', emoji: '🇮🇳' },
    { code: 'kn_IN', name: 'Kannada', shortcut: 'KN', emoji: '🇮🇳' },
    { code: 'si_LK', name: 'Sinhala', shortcut: 'SI', emoji: '🇱🇰' },
    { code: 'ne_NP', name: 'Nepali', shortcut: 'NE', emoji: '🇳🇵' },

    // --- Middle East, Central & Western Asia ---
    { code: 'fa_IR', name: 'Persian (Farsi)', shortcut: 'FA', emoji: '🇮🇷' },
    { code: 'ps_AF', name: 'Pashto', shortcut: 'PS', emoji: '🇦🇫' },
    { code: 'he_IL', name: 'Hebrew', shortcut: 'HE', emoji: '🇮🇱' },
    { code: 'az_AZ', name: 'Azerbaijani', shortcut: 'AZ', emoji: '🇦🇿' },
    { code: 'hy_AM', name: 'Armenian', shortcut: 'HY', emoji: '🇦🇲' },
    { code: 'ka_GE', name: 'Georgian', shortcut: 'KA', emoji: '🇬🇪' },
    { code: 'kk_KZ', name: 'Kazakh', shortcut: 'KK', emoji: '🇰🇿' },
    { code: 'mn_MN', name: 'Mongolian', shortcut: 'MN', emoji: '🇲🇳' },
    { code: 'ky_KG', name: 'Kyrgyz', shortcut: 'KY', emoji: '🇰🇬' },
    { code: 'tg_TJ', name: 'Tajik', shortcut: 'TG', emoji: '🇹🇯' },
    { code: 'tk_TM', name: 'Turkmen', shortcut: 'TK', emoji: '🇹🇲' },
    { code: 'ku_TR', name: 'Kurdish', shortcut: 'KU', emoji: '🇹🇷' },

    // --- Africa ---
    { code: 'sw_KE', name: 'Swahili', shortcut: 'SW', emoji: '🇰🇪' },
    { code: 'yo_NG', name: 'Yoruba', shortcut: 'YO', emoji: '🇳🇬' },
    { code: 'ig_NG', name: 'Igbo', shortcut: 'IG', emoji: '🇳🇬' },
    { code: 'ha_NE', name: 'Hausa', shortcut: 'HA', emoji: '🇳🇪' },
    { code: 'am_ET', name: 'Amharic', shortcut: 'AM', emoji: '🇪🇹' },
    { code: 'zu_ZA', name: 'Zulu', shortcut: 'ZU', emoji: '🇿🇦' },
    { code: 'xh_ZA', name: 'Xhosa', shortcut: 'XH', emoji: '🇿🇦' },
    { code: 'st_LS', name: 'Southern Sotho', shortcut: 'ST', emoji: '🇱🇸' },
    { code: 'sn_ZW', name: 'Shona', shortcut: 'SN', emoji: '🇿🇼' },
    { code: 'rw_RW', name: 'Kinyarwanda', shortcut: 'RW', emoji: '🇷🇼' },
    { code: 'so_SO', name: 'Somali', shortcut: 'SO', emoji: '🇸🇴' },
    { code: 'ny_MW', name: 'Chichewa', shortcut: 'NY', emoji: '🇲🇼' },
    { code: 'mg_MG', name: 'Malagasy', shortcut: 'MG', emoji: '🇲🇬' },
    { code: 'om_ET', name: 'Oromo', shortcut: 'OM', emoji: '🇪🇹' },
    { code: 'ti_ET', name: 'Tigrinya', shortcut: 'TI', emoji: '🇪🇷' },

    // --- Americas ---
    { code: 'pt_BR', name: 'Portuguese (Brazil)', shortcut: 'PT-BR', emoji: '🇧🇷' },
    { code: 'es_MX', name: 'Spanish (Mexico)', shortcut: 'ES-MX', emoji: '🇲🇽' },
    { code: 'fr_CA', name: 'French (Canada)', shortcut: 'FR-CA', emoji: '🇨🇦' },
    { code: 'qu_PE', name: 'Quechua', shortcut: 'QU', emoji: '🇵🇪' },
    { code: 'gn_PY', name: 'Guarani', shortcut: 'GN', emoji: '🇵🇾' },
    { code: 'ay_BO', name: 'Aymara', shortcut: 'AY', emoji: '🇧🇴' },
    { code: 'ht_HT', name: 'Haitian Creole', shortcut: 'HT', emoji: '🇭🇹' },

    // --- Constructed & Other ---
    { code: 'eo_XX', name: 'Esperanto', shortcut: 'EO', emoji: '🌍' },
    { code: 'la_VA', name: 'Latin', shortcut: 'LA', emoji: '🇻🇦' },
    { code: 'auto', name: 'Auto Detect', shortcut: 'AUTO', emoji: '🔍' },
];