export const LANGUAGE_OPTIONS = [
    // --- Your original order (preferred) ---
    { code: 'en_XX', name: 'English', shortcut: 'EN' },
    { code: 'cs_CZ', name: 'Czech', shortcut: 'CS' },
    { code: 'it_IT', name: 'Italian', shortcut: 'IT' },
    { code: 'fr_XX', name: 'French', shortcut: 'FR' },
    { code: 'de_DE', name: 'German', shortcut: 'DE' },
    { code: 'es_XX', name: 'Spanish', shortcut: 'ES' },
    { code: 'ru_RU', name: 'Russian', shortcut: 'RU' },
    { code: 'zh_CN', name: 'Chinese (Simplified)', shortcut: 'ZH' },
    { code: 'ar_AR', name: 'Arabic', shortcut: 'AR' },
    { code: 'hi_IN', name: 'Hindi', shortcut: 'HI' },
    { code: 'pl_PL', name: 'Polish', shortcut: 'PL' },
    { code: 'pt_XX', name: 'Portuguese', shortcut: 'PT' },
    { code: 'tr_TR', name: 'Turkish', shortcut: 'TR' },
    { code: 'vi_VN', name: 'Vietnamese', shortcut: 'VI' },

    // --- European ---
    { code: 'nl_NL', name: 'Dutch', shortcut: 'NL' },
    { code: 'sv_SE', name: 'Swedish', shortcut: 'SV' },
    { code: 'da_DK', name: 'Danish', shortcut: 'DA' },
    { code: 'fi_FI', name: 'Finnish', shortcut: 'FI' },
    { code: 'no_NO', name: 'Norwegian', shortcut: 'NO' },
    { code: 'is_IS', name: 'Icelandic', shortcut: 'IS' },
    { code: 'ro_RO', name: 'Romanian', shortcut: 'RO' },
    { code: 'hu_HU', name: 'Hungarian', shortcut: 'HU' },
    { code: 'bg_BG', name: 'Bulgarian', shortcut: 'BG' },
    { code: 'el_GR', name: 'Greek', shortcut: 'EL' },
    { code: 'hr_HR', name: 'Croatian', shortcut: 'HR' },
    { code: 'uk_UA', name: 'Ukrainian', shortcut: 'UK' },
    { code: 'sk_SK', name: 'Slovak', shortcut: 'SK' },
    { code: 'sl_SI', name: 'Slovenian', shortcut: 'SL' },
    { code: 'lt_LT', name: 'Lithuanian', shortcut: 'LT' },
    { code: 'lv_LV', name: 'Latvian', shortcut: 'LV' },
    { code: 'et_EE', name: 'Estonian', shortcut: 'ET' },
    { code: 'sr_RS', name: 'Serbian', shortcut: 'SR' },
    { code: 'mk_MK', name: 'Macedonian', shortcut: 'MK' },
    { code: 'bs_BA', name: 'Bosnian', shortcut: 'BS' },
    { code: 'sq_AL', name: 'Albanian', shortcut: 'SQ' },
    { code: 'mt_MT', name: 'Maltese', shortcut: 'MT' },
    { code: 'ga_IE', name: 'Irish', shortcut: 'GA' },
    { code: 'cy_GB', name: 'Welsh', shortcut: 'CY' },
    { code: 'ca_ES', name: 'Catalan', shortcut: 'CA' },
    { code: 'eu_ES', name: 'Basque', shortcut: 'EU' },
    { code: 'gl_ES', name: 'Galician', shortcut: 'GL' },
    { code: 'af_ZA', name: 'Afrikaans', shortcut: 'AF' },

    // --- East Asia & Oceania ---
    { code: 'zh_TW', name: 'Chinese (Traditional)', shortcut: 'ZH-TW' },
    { code: 'ja_XX', name: 'Japanese', shortcut: 'JA' },
    { code: 'ko_KR', name: 'Korean', shortcut: 'KO' },
    { code: 'th_TH', name: 'Thai', shortcut: 'TH' },
    { code: 'id_ID', name: 'Indonesian', shortcut: 'ID' },
    { code: 'ms_MY', name: 'Malay', shortcut: 'MS' },
    { code: 'fil_PH', name: 'Filipino', shortcut: 'FIL' },
    { code: 'tl_PH', name: 'Tagalog', shortcut: 'TL' },
    { code: 'ceb_PH', name: 'Cebuano', shortcut: 'CEB' },
    { code: 'jv_ID', name: 'Javanese', shortcut: 'JV' },
    { code: 'su_ID', name: 'Sundanese', shortcut: 'SU' },

    // --- South Asia ---
    { code: 'bn_BD', name: 'Bengali', shortcut: 'BN' },
    { code: 'ur_PK', name: 'Urdu', shortcut: 'UR' },
    { code: 'ta_IN', name: 'Tamil', shortcut: 'TA' },
    { code: 'te_IN', name: 'Telugu', shortcut: 'TE' },
    { code: 'ml_IN', name: 'Malayalam', shortcut: 'ML' },
    { code: 'gu_IN', name: 'Gujarati', shortcut: 'GU' },
    { code: 'mr_IN', name: 'Marathi', shortcut: 'MR' },
    { code: 'pa_IN', name: 'Punjabi', shortcut: 'PA' },
    { code: 'kn_IN', name: 'Kannada', shortcut: 'KN' },
    { code: 'si_LK', name: 'Sinhala', shortcut: 'SI' },
    { code: 'ne_NP', name: 'Nepali', shortcut: 'NE' },

    // --- Middle East, Central & Western Asia ---
    { code: 'fa_IR', name: 'Persian (Farsi)', shortcut: 'FA' },
    { code: 'ps_AF', name: 'Pashto', shortcut: 'PS' },
    { code: 'he_IL', name: 'Hebrew', shortcut: 'HE' },
    { code: 'az_AZ', name: 'Azerbaijani', shortcut: 'AZ' },
    { code: 'hy_AM', name: 'Armenian', shortcut: 'HY' },
    { code: 'ka_GE', name: 'Georgian', shortcut: 'KA' },
    { code: 'kk_KZ', name: 'Kazakh', shortcut: 'KK' },
    { code: 'mn_MN', name: 'Mongolian', shortcut: 'MN' },
    { code: 'ky_KG', name: 'Kyrgyz', shortcut: 'KY' },
    { code: 'tg_TJ', name: 'Tajik', shortcut: 'TG' },
    { code: 'tk_TM', name: 'Turkmen', shortcut: 'TK' },
    { code: 'ku_TR', name: 'Kurdish', shortcut: 'KU' },

    // --- Africa ---
    { code: 'sw_KE', name: 'Swahili', shortcut: 'SW' },
    { code: 'yo_NG', name: 'Yoruba', shortcut: 'YO' },
    { code: 'ig_NG', name: 'Igbo', shortcut: 'IG' },
    { code: 'ha_NE', name: 'Hausa', shortcut: 'HA' },
    { code: 'am_ET', name: 'Amharic', shortcut: 'AM' },
    { code: 'zu_ZA', name: 'Zulu', shortcut: 'ZU' },
    { code: 'xh_ZA', name: 'Xhosa', shortcut: 'XH' },
    { code: 'st_LS', name: 'Southern Sotho', shortcut: 'ST' },
    { code: 'sn_ZW', name: 'Shona', shortcut: 'SN' },
    { code: 'rw_RW', name: 'Kinyarwanda', shortcut: 'RW' },
    { code: 'so_SO', name: 'Somali', shortcut: 'SO' },
    { code: 'ny_MW', name: 'Chichewa', shortcut: 'NY' },
    { code: 'ln_CD', name: 'Lingala', shortcut: 'LN' },
    { code: 'mg_MG', name: 'Malagasy', shortcut: 'MG' },
    { code: 'yo_BJ', name: 'Yoruba (Benin)', shortcut: 'YO-BJ' },


    // --- Others / Extra coverage ---
    { code: 'km_KH', name: 'Khmer', shortcut: 'KM' },
    { code: 'lo_LA', name: 'Lao', shortcut: 'LO' },
    { code: 'my_MM', name: 'Burmese', shortcut: 'MY' },
    { code: 'uz_UZ', name: 'Uzbek', shortcut: 'UZ' },
    { code: 'be_BY', name: 'Belarusian', shortcut: 'BE' },
    { code: 'sh_BA', name: 'Serbo-Croatian', shortcut: 'SH' },
    { code: 'lb_LU', name: 'Luxembourgish', shortcut: 'LB' },
    { code: 'fo_FO', name: 'Faroese', shortcut: 'FO' },
    { code: 'os_RU', name: 'Ossetian', shortcut: 'OS' },
    { code: 'ba_RU', name: 'Bashkir', shortcut: 'BA' },
    { code: 'tt_RU', name: 'Tatar', shortcut: 'TT' },
    { code: 'cv_RU', name: 'Chuvash', shortcut: 'CV' },
    { code: 'sah_RU', name: 'Sakha', shortcut: 'SAH' },
    { code: 'bho_IN', name: 'Bhojpuri', shortcut: 'BHO' },
    { code: 'as_IN', name: 'Assamese', shortcut: 'AS' },
    { code: 'or_IN', name: 'Odia (Oriya)', shortcut: 'OR' },
    { code: 'br_FR', name: 'Breton', shortcut: 'BR' },
    { code: 'oc_FR', name: 'Occitan', shortcut: 'OC' },
    { code: 'rm_CH', name: 'Romansh', shortcut: 'RM' },
    { code: 'sc_IT', name: 'Sardinian', shortcut: 'SC' },
    { code: 'gd_GB', name: 'Scottish Gaelic', shortcut: 'GD' },
    { code: 'sm_WS', name: 'Samoan', shortcut: 'SM' },
    { code: 'to_TO', name: 'Tongan', shortcut: 'TO' },
    { code: 'haw_US', name: 'Hawaiian', shortcut: 'HAW' },

    // --- Rare / regional / special ---
    { code: 'dz_BT', name: 'Dzongkha (Bhutan)', shortcut: 'DZ' },
    { code: 'lu_CD', name: 'Luba-Katanga', shortcut: 'LU' },
    { code: 'ss_SZ', name: 'Swati', shortcut: 'SS' },
    { code: 'tn_BW', name: 'Tswana', shortcut: 'TN' },
    { code: 've_ZA', name: 'Venda', shortcut: 'VE' },
    { code: 'ts_ZA', name: 'Tsonga', shortcut: 'TS' },
    { code: 'kg_CG', name: 'Kongo', shortcut: 'KG' },
    { code: 'sg_CF', name: 'Sango', shortcut: 'SG' },

    // --- Dialect/variant examples ---
    { code: 'es_MX', name: 'Spanish (Mexico)', shortcut: 'ES-MX' },
    { code: 'es_AR', name: 'Spanish (Argentina)', shortcut: 'ES-AR' },
    { code: 'fr_CA', name: 'French (Canada)', shortcut: 'FR-CA' },
    { code: 'pt_BR', name: 'Portuguese (Brazil)', shortcut: 'PT-BR' },
    { code: 'en_GB', name: 'English (UK)', shortcut: 'EN-GB' },
    { code: 'en_US', name: 'English (US)', shortcut: 'EN-US' },
    { code: 'zh_HK', name: 'Chinese (Hong Kong)', shortcut: 'ZH-HK' },

    // Add any more languages here if you find support for them!
];